import type { Metadata } from "next";
import "./globals.css";

import AboutMe from "@/app/(components)/AboutMe";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative flex justify-center items-center bg-gradient-to-b from-black to-black/90">
        {children}
        <AboutMe/>
      </body>
    </html>
  );
}
